server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        # 默认30天
        max-age: 2592000
spring:
  session:
    store-type: redis
    # 默认30天
    time-to-live: 2592000
  profiles:
    active: local
  application:
    name: yu-picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupicture
    username: root
    password: abc123
  servlet:
    multipart:
      max-file-size: 2MB
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    password: 123456
mybatis-plus:
  configuration:
    # MyBatis 配置，map-underscore-to-camel-case为驼峰的配置
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 全局配置
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yupi.yupicturebackend.controller